import type { AppCopy } from './copy';

export const homesteadCopy: AppCopy = {
  brand: {
    name: 'Homestead',
    legal: 'Homestead',
    pressLine: 'Homestead Press · Est. 2025',
    tagline: 'built for the people who keep your family running.',
    quote: '"It takes a village."',
  },
  urgentSignal: {
    noun: 'Bell',
    actionLabel: 'Ring the Bell',
    tabLabel: 'Bell',
    tabIcon: '🔔',
    towerTitle: 'Bell Tower',
    pushTitle: (household: string) => `🔔 ${household} needs help`,
    pushBody: (reason: string, note?: string) => reason + (note ? ` — ${note}` : ''),
    escalateTitle: (reason: string) => `🔔 Still needed — ${reason}`,
    escalateBody: 'Inner circle unavailable. Can you help?',
    respondedTitles: {
      onWay: (name: string) => `✅ ${name} is on the way`,
      thirty: (name: string) => `⏱ ${name} can help in 30 min`,
      cannot: (name: string) => `${name} can't make it`,
    },
    respondedBodies: {
      onWay: 'Bell handled — someone is coming.',
      thirty: 'Still looking for someone sooner…',
      cannot: 'Bell continuing to next circle…',
    },
    deepLinkTab: 'bell',
    tagPrefix: 'bell',
    escalateTagPrefix: 'bell-escalate',
    respondedTagPrefix: 'bell-handled',
    thirtyTagPrefix: 'bell-thirty',
    cannotTagPrefix: 'bell-cannot',
  },
  request: {
    newLabel: 'New shift',
    acceptVerb: 'Claim',
    tabLabel: 'Shifts',
    pushTitle: (household: string) => `📋 New shift — ${household}`,
    pushTitleTargeted: (household: string) => `📋 ${household} needs you`,
    coveredTitle: (name: string) => `✅ ${name} is on it`,
    releasedTitle: (name: string) => `↩️ ${name} released your shift`,
    releasedBody: (title: string, when: string) => `"${title}" · ${when} — now open again`,
    cancelledTitle: '❌ Shift cancelled',
    deepLinkTab: 'almanac',
    shiftsDeepLinkTab: 'shifts',
    tagPrefix: 'shift',
    claimedTagPrefix: 'claimed',
    releasedTagPrefix: 'released',
    cancelTagPrefix: 'cancel',
  },
  innerRing: {
    listTitle: 'Inner Circle',
    tabLabel: 'Inner Circle',
    dbValue: 'inner_circle' as const,
  },
  outerRing: {
    listTitle: 'Sitters',
    tabLabel: 'Sitters',
    dbValue: 'sitter' as const,
  },
  circle: {
    title: 'The Village',
    innerLabel: 'Inner Circle',
    outerLabel: 'Trusted Sitters',
    loadingState: 'Loading your village…',
    emptyState: 'Your village is empty.',
  },
  roles: {
    keeper: { singular: 'Parent', plural: 'Parents' },
    watcher: { singular: 'Caregiver', plural: 'Caregivers' },
  },
  icalendar: {
    prodId: '-//Homestead//Shifts//EN',
    calName: 'Homestead Shifts',
    uidDomain: 'homestead.app',
    filename: 'homestead-shifts.ics',
  },
  emails: {
    contact: 'hello@homestead.app',
    notify: 'notify@homestead.app',
  },
  api: {
    urgentSignal: '/api/bell',
    request: '/api/shifts',
    circle: '/api/village',
  },
  guide: {
    whatIsTitle: 'What is Homestead?',
    whatIsBody1: 'Homestead is a private coordination app for families who rely on a village of caregivers — grandparents, sitters, close friends — to keep life running. It\'s not a marketplace. Everyone here already knows each other.',
    whatIsBody2: 'Parents post what they need. Caregivers claim it or respond to urgent bells. No group texts, no scheduling back-and-forth.',
    parentSection: 'For Parents',
    caregiverSection: 'For Caregivers',
    tipsTitle: 'Tips for everyone',
    tipsSub: 'Getting the most out of Homestead',
    footerQuote: '"It takes a village."',
    footerTagline: 'Homestead — built for the people who keep your family running.',
  },
};
