import type { AppCopy } from './copy';

export const coveyCopy: AppCopy = {
  brand: {
    name: 'Covey',
    legal: 'Covey & Co.',
    pressLine: 'Covey & Co. · Est. 2025',
    tagline: 'the small, watching circle around your chicks.',
    quote: '"Tail to tail. Heads out."',
    // Founding thesis — use on press/about pages, pitch decks, guide screen footer
    thesis: '"The small, watching circle is the unit of human flourishing that software has spent twenty years dissolving. The work of the next twenty is to put it back."',
  },
  urgentSignal: {
    noun: 'Lantern',
    actionLabel: 'Light the Lantern',
    tabLabel: 'Lantern',
    tabIcon: '🪔',
    towerTitle: 'Lantern Tower',
    pushTitle: (household: string) => `🪔 ${household} needs help`,
    pushBody: (reason: string, note?: string) => reason + (note ? ` — ${note}` : ''),
    escalateTitle: (reason: string) => `🪔 Still needed — ${reason}`,
    escalateBody: 'Your Covey didn\'t answer. Can you help?',
    respondedTitles: {
      onWay: (name: string) => `✅ ${name} is on the way`,
      thirty: (name: string) => `⏱ ${name} can cover in 30 min`,
      cannot: (name: string) => `${name} can't cover`,
    },
    respondedBodies: {
      onWay: 'Lantern answered — someone is coming.',
      thirty: 'Still looking for someone sooner…',
      cannot: 'Lantern moving to the Field…',
    },
    deepLinkTab: 'lantern',
    tagPrefix: 'lantern',
    escalateTagPrefix: 'lantern-escalate',
    respondedTagPrefix: 'lantern-handled',
    thirtyTagPrefix: 'lantern-thirty',
    cannotTagPrefix: 'lantern-cannot',
  },
  request: {
    newLabel: 'New Whistle',
    acceptVerb: 'Cover',
    tabLabel: 'Whistles',
    pushTitle: (household: string) => `📋 New Whistle — ${household}`,
    pushTitleTargeted: (household: string) => `📋 ${household} needs you`,
    coveredTitle: (name: string) => `✅ ${name} covered it`,
    releasedTitle: (name: string) => `↩️ ${name} released your Whistle`,
    releasedBody: (title: string, when: string) => `"${title}" · ${when} — open again`,
    cancelledTitle: '❌ Whistle cancelled',
    claimerConfirmTitle: (title: string) => `✅ You covered "${title}"`,
    claimerConfirmBody: (when: string) => `${when} — added to your shifts`,
    deepLinkTab: 'perch',
    shiftsDeepLinkTab: 'whistles',
    tagPrefix: 'whistle',
    claimedTagPrefix: 'covered',
    claimerConfirmTagPrefix: 'covered-self',
    releasedTagPrefix: 'released',
    cancelTagPrefix: 'cancel',
  },
  innerRing: {
    listTitle: 'Your Covey',
    tabLabel: 'Covey',
    dbValue: 'covey' as const,
  },
  outerRing: {
    listTitle: 'Your Field',
    tabLabel: 'Field',
    dbValue: 'field' as const,
  },
  schedule: {
    title: 'The Perch',
    caregiverTitle: 'Open Whistles',
  },
  circle: {
    title: 'The Covey',
    tabLabel: 'Covey',
    caregiverTitle: 'Covies',
    innerLabel: 'Covey',
    outerLabel: 'Field',
    innerNote: 'First to answer · always on call',
    outerNote: 'Available on request · paid caregivers',
    familyLabel: 'Family',
    familyNote: 'Parents and chicks.',
    kidLabel: 'Chick',
    loadingState: 'Loading The Covey…',
    emptyState: 'The Covey is quiet.',
    quote: 'Expand your safety net. Build your covey.',
    networkLabel: 'covey',
  },
  roles: {
    keeper: { singular: 'Keeper', plural: 'Keepers' },
    watcher: { singular: 'Watcher', plural: 'Watchers' },
  },
  icalendar: {
    prodId: '-//Covey//Whistles//EN',
    calName: 'Covey Whistles',
    uidDomain: 'joincovey.co',
    filename: 'covey-whistles.ics',
  },
  emails: {
    contact: 'hello@sirmans.co',
    notify: 'notify@sirmans.co',
  },
  guide: {
    whatIsTitle: 'What is Covey?',
    whatIsBody1: 'Covey is a private coordination app for families who rely on a small, trusted circle — grandparents, close friends, the neighbor with the spare key — to keep life running. It\'s not a marketplace. Everyone here already knows each other.',
    whatIsBody2: 'Keepers send Whistles. Watchers cover them. When something is urgent, one tap lights the Lantern. No group texts, no back-and-forth.',
    parentSection: 'For Keepers',
    caregiverSection: 'For Watchers',
    tipsTitle: 'Tips for everyone',
    tipsSub: 'Getting the most out of Covey',
    footerQuote: '"Tail to tail. Heads out."',
    footerTagline: 'Covey — the small, watching circle around your children.',
  },
};
